Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2023-11, with the labels that each got.

#207 Issue 53 additional updates
  cmd/analyzer/main.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/experiments_env_all_vpcs.json
  pkg/ibmvpc/examples/experiments_env_all_vpcs.txt
  pkg/ibmvpc/examples/experiments_env_test-vpc1-ky.json
  pkg/ibmvpc/examples/experiments_env_test-vpc2-ky.json
  pkg/ibmvpc/examples/multiple_vpcs_all_vpcssubnetsBased_withPGW.txt
  pkg/ibmvpc/parser.go
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/textOutput.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/XXL

#208 166 single group element
  pkg/vpcmodel/grouping.go
Labels: size/M

#206 163 semantic diff ip
  pkg/vpcmodel/diffSubnets_test.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiffSubnets.go
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/XL

#218 Fix issue sg testing 3
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input_sg_testing_3.json
  pkg/ibmvpc/examples/sg_testing_3.txt
  pkg/ibmvpc/examples/sg_testing_3subnetsBased_withPGW.txt
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/externalNetwork.go
Labels: size/XXL

#222 EndpointElem -> VPCResourceIntf
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/semanticDiffSubnets.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/M

#224 ignore fip without target, instead of returning an error
  pkg/ibmvpc/parser.go
Labels: size/S

#223 163 output txt fmt
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt
  pkg/vpcmodel/diffSubnets_test.go
  pkg/vpcmodel/semanticDiffSubnets.go
Labels: size/L

#227 211 vsis
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt
  pkg/ibmvpc/examples/input_acl_testing3_2nd.json
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/diffSubnets_test.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/textOutput.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/XXL

#230 209 grouping semantic diff new
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/L

#235 issue #234: extend grouping types to include actual conn and diff obj…
  pkg/common/connectionset.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
Labels: size/L

#236 201 semantic diff outputs
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/common/connectionset.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.json
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.md
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.json
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.md
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/textOutput.go
Labels: size/XL
