Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2023-12, with the labels that each got.

#244 README for diff analysis types
  README.md
  cmd/analyzer/parse_args.go
Labels: size/S

#253 end-to-end test for semantic diff to include several types of differe…
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input_sg_testing1_new_2nd.json
  pkg/ibmvpc/examples/sg_testing1_newendpointsDiff.txt
Labels: size/XXL

#246 231 unify connectivity maps
  pkg/vpcmodel/commonConnectivity.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/L

#247 initial tgw support
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing3.md
  pkg/ibmvpc/examples/acl_testing3.txt
  pkg/ibmvpc/examples/acl_testing3_analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/acl_testing3_with_grouping.txt
  pkg/ibmvpc/examples/acl_testing3_with_two_vpcs.txt
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.md
  pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt
  pkg/ibmvpc/examples/acl_testing5_oldsubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/acl_testing5subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.md
  pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt
  pkg/ibmvpc/examples/demo_with_instances.md
  pkg/ibmvpc/examples/demo_with_instances.txt
  pkg/ibmvpc/examples/demo_with_instances_analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/demo_with_instances_vpes.txt
  pkg/ibmvpc/examples/demo_with_instances_with_grouping.txt
  pkg/ibmvpc/examples/demo_with_instancessubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/experiments_env_all_vpcs.txt
  pkg/ibmvpc/examples/experiments_env_test-vpc1-ky.txt
  pkg/ibmvpc/examples/experiments_env_test-vpc2-ky.txt
  pkg/ibmvpc/examples/iks_config_object_with_grouping.txt
  pkg/ibmvpc/examples/input_tgw_basic_example.json
  pkg/ibmvpc/examples/multiple_vpcs_all_vpcssubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/multiple_vpcs_ky-testenv-vpcsubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/multiple_vpcs_test-vpc-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/sg_testing1_new.md
  pkg/ibmvpc/examples/sg_testing1_new.txt
  pkg/ibmvpc/examples/sg_testing1_new_analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/sg_testing1_new_groupingsubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/sg_testing1_new_with_grouping.txt
  pkg/ibmvpc/examples/sg_testing1_newendpointsDiff.txt
  pkg/ibmvpc/examples/sg_testing1_newsubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/sg_testing_3.txt
  pkg/ibmvpc/examples/sg_testing_3subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_basic_example_all_vpcs.txt
  pkg/ibmvpc/examples/tgw_basic_example_all_vpcssubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_basic_example_combined-vpc-local-tg-ky.txt
  pkg/ibmvpc/examples/tgw_basic_example_combined-vpc-local-tg-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_basic_example_ky-vpc1.txt
  pkg/ibmvpc/examples/tgw_basic_example_ky-vpc1subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_basic_example_ky-vpc2.txt
  pkg/ibmvpc/examples/tgw_basic_example_ky-vpc2subnetsBased_withPGW.txt
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/textOutput.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/XXL

#261 42 explanability 1
  cmd/analyzer/main.go
  pkg/ibmvpc/sg_analysis.go
  pkg/vpcmodel/nodesExplainability..go
Labels: size/M

#262 add tgw example
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input_tgw_larger_example.json
  pkg/ibmvpc/examples/tgw_larger_example_all_vpcs.txt
  pkg/ibmvpc/examples/tgw_larger_example_all_vpcssubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_combined-vpc-local-tg-ky.txt
  pkg/ibmvpc/examples/tgw_larger_example_combined-vpc-local-tg-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_combined-vpc-local-tg-zn.txt
  pkg/ibmvpc/examples/tgw_larger_example_combined-vpc-local-tg-znsubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc0-ky.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc0-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc1-ky.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc1-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc2-ky.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc2-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc3-ky.txt
  pkg/ibmvpc/examples/tgw_larger_example_test-vpc3-kysubnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_zn-vpc1.txt
  pkg/ibmvpc/examples/tgw_larger_example_zn-vpc1subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/tgw_larger_example_zn-vpc2.txt
  pkg/ibmvpc/examples/tgw_larger_example_zn-vpc2subnetsBased_withPGW.txt
Labels: size/XXL

#268 allow getting the version using a command-line flag: analyzer-version
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/version/version.go
  release/create.sh
Labels: size/M

#266 42 explanability 2
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/nodesExplainability..go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/L

#279 Explainability: printing connection
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/M

#287 issue #157 : import the jsonio package from vpc-network-config-synthesis
  .github/workflows/go-test.yml
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
  pkg/common/connectionset.go
  pkg/common/data_model.go
Labels: size/XL

#277 handle unsupported args
  cmd/analyzer/parse_args.go
Labels: size/M

#286 281 explainability default
  pkg/common/ipBlock.go
  pkg/ibmvpc/examples/input_sg_testing_default.json
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/XXL

#285 improve cli command-line help
  README.md
  cmd/analyzer/parse_args.go
Labels: size/L

#298 fix issue #237 : use network interface ID instead of PrimaryIP.ID
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs_.json
  pkg/ibmvpc/examples/demo_with_instances_ky-testenv-vpc.json
  pkg/ibmvpc/examples/experiments_env_all_vpcs_.json
  pkg/ibmvpc/examples/experiments_env_test-vpc1-ky.json
  pkg/ibmvpc/examples/experiments_env_test-vpc2-ky.json
  pkg/ibmvpc/parser.go
Labels: size/XXL

#295 290 explainability external ip
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/L
