Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-01, with the labels that each got.

#299 issue #256 : change NameToResource to be UIDToResource
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/parser.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/M

#245 subnet-grouping2
  .github/workflows/go-test.yml
  .github/workflows/golangci-lint.yml
  cmd/analyzer/main_test.go
  pkg/common/genericSet.go
  pkg/drawio/abstractTreeNode.go
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/layoutOverlap.go
  pkg/drawio/lineTreeNode.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
  pkg/drawio/subnetsLayout.go
  pkg/drawio/treeNodeInterface.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/grouping_test.go
Labels: size/XXL

#307 Update minimally required go version
  README.md
Labels: size/XS

#308 linter: avoid printing lines of code with problems
  .golangci.yml
Labels: size/XS

#301 290 explainability public ip grouping
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/L

#311 Better zone indexes
  pkg/drawio/drawio_test.go
  pkg/drawio/subnetsLayout.go
Labels: size/L

#312 302 explainabilty query connection
  pkg/ibmvpc/examples/input_sg_testing1_new.json
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/L

#316 Skip cache to fix false linter errors: file exists
  .github/workflows/golangci-lint.yml
Labels: size/XS

#314 Support md output format with all_subnets analysis type
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing5_all_vpcs_subnetsBased_withPGW.md
  pkg/ibmvpc/examples/acl_testing5_old_all_vpcs_subnetsBased_withPGW.md
  pkg/vpcmodel/mdOutput.go
Labels: size/M

#297 add info message just when needed
  pkg/ibmvpc/examples/acl_testing5_all_vpcs_subnetsBased_withPGW.md
  pkg/ibmvpc/examples/acl_testing5_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/acl_testing5_old_all_vpcs_subnetsBased_withPGW.md
  pkg/ibmvpc/examples/acl_testing5_old_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs_.md
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs_.txt
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs__debug.txt
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/demo_with_instances_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/demo_with_instances_vpes_all_vpcs_.txt
  pkg/ibmvpc/examples/experiments_env_all_vpcs_.txt
  pkg/ibmvpc/examples/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/multiple_vpcs_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_.md
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs__debug.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/sg_testing1_new_grouping_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/ibmvpc/examples/tgw_basic_example_all_vpcs_.txt
  pkg/ibmvpc/examples/tgw_basic_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/textOutput.go
Labels: size/L

#319 accept a description of a connection in the cli and translate it to co…
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/vpcmodel/output.go
Labels: size/L

#283 Issue 134 - consume from the collector the ResourcesContainter
  cmd/analyzer/main_test.go
  go.mod
  go.sum
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/parser.go
Labels: size/XL

#323 add tgw example with collection from all regions
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input_tgw_basic_example_multiple_regions.json
  pkg/ibmvpc/examples/tgw_basic_example_multiple_regions_all_vpcs_.txt
  pkg/ibmvpc/examples/tgw_basic_example_multiple_regions_all_vpcs_subnetsBased_withPGW.txt
Labels: size/XXL

#320 313 explain add routing resources
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L

#326 connect explainConnectivity to main cli
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/acl_testing3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_explain.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/textOutput.go
Labels: size/L

#329 Extend tgw support prefix filters
  go.mod
  pkg/common/ipBlock.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
Labels: size/L

#334 318 improve unitests
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/output.go
Labels: size/XL

#338 add explain mode args to help usage
  README.md
  cmd/analyzer/parse_args.go
Labels: size/M

#345 Bump github.com/np-guard/cloud-resource-collector from 0.4.0 to 0.5.1
  cmd/analyzer/main_test.go
  go.mod
  go.sum
  pkg/ibmvpc/examples/input_obj_from_issue_342.json
Labels: size/XXL

#341 322 nacl query
  pkg/ibmvpc/examples/acl_testing3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/input_acl_testing3_3rd.json
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_explain.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/nodesExplainability.go
Labels: size/XXL

#350 fix release automation
  release/create.sh
  release/tag.sh
Labels: size/M

#351 42 explainability query conn intersect
  pkg/ibmvpc/examples/sg_testing1_new_all_vpcs_explain.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/sg_analysis.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/textOutput.go
Labels: size/M
