Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-02, with the labels that each got.

#352 Handle subnet overlap
  pkg/drawio/abstractTreeNode.go
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/lineTreeNode.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
  pkg/drawio/subnetLayoutOverlap.go
  pkg/drawio/subnetsLayout.go
  pkg/drawio/treeNodeInterface.go
Labels: size/XL

#364 improve unit tests
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/explainability_test.go
Labels: size/L

#361 overlap for src-dest with the same center in drawio
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/subnetLayoutOverlap.go
Labels: size/M

#366 Adding more linters and fixing the errors they found
  .golangci.yml
  cmd/analyzer/main.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/nodesConnectivity.go
Labels: size/M

#367 connect internal address to a vsi
  pkg/vpcmodel/nodesExplainability.go
Labels: size/S

#371 extend input to VSI
  pkg/vpcmodel/nodesExplainability.go
Labels: size/S

#382 accept plain IPs in explainability
  pkg/vpcmodel/nodesExplainability.go
Labels: size/XS

#384 Moving intervals to models repo
  go.mod
  go.sum
  pkg/common/CanonicalHypercubeSet.go
  pkg/common/CanonicalIntervalSet.go
  pkg/common/HCset_test.go
  pkg/common/connectionset.go
  pkg/common/ipBlock.go
Labels: size/L

#383 simplify input nodes for `getRoutingResource` - no need for `getContainingConfigNode`
  pkg/vpcmodel/nodesExplainability.go
Labels: size/S

#385 Hypercubes moved to models repo
  go.mod
  go.sum
  pkg/common/CanonicalHypercubeSet.go
  pkg/common/HCset_test.go
  pkg/common/connectionset.go
Labels: size/XL

#386 Improve connectivity report output headers
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsBased_withPGW.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_old_all_vpcs_subnetsBased_withPGW.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_old_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs__analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_vpes_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/experiments_env_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/multiple_vpcs_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs__analysisPerSubnetSeparately.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_grouping_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_multiple_regions_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_multiple_regions_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/textOutput.go
Labels: size/L

#390 379 connect vsi internal ip input
  README.md
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/examples/input/input_sg_testing1_new.json
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternalSrcTo4DstInternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/printExplain.go
  pkg/vpcmodel/textOutput.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/XXL

#399 Adding setup-go action for CodeQL to work with Go 1.21
  .github/workflows/codeql-analysis.yml
Labels: size/XS

#389 issue 359 updates for statefulness analysis
  pkg/common/connectionset.go
  pkg/common/statefulness.go
  pkg/common/statefulness_test.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/XXL

#394 Ipblock model issues
  pkg/common/ipBlock.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/nodesExplainability.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/utils.go
Labels: size/XL

#405 do not print vsis-diff-info: when empty
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs_endpointsDiff.txt
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
Labels: size/L

#396 issue #324: small fixes
  pkg/ibmvpc/parser.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/utils.go
Labels: size/M

#406 issue #397: add InternalNode interface + use ExternalNode where possible
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/experiments_env_all_vpcs_.json
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff.go
Labels: size/XXL

#403 mode to read resources directly from the account (using the collector package)
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  go.mod
  go.sum
Labels: size/L

#410 Consuming ipblocks package from models repo
  go.mod
  go.sum
  pkg/common/ipBlock.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/connectivity_result.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/XL

#413 set cloud name for tgw vpc
  pkg/ibmvpc/parser.go
Labels: size/XS

#411 Layout tgw
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/lineTreeNode.go
  pkg/vpcmodel/drawioOutput.go
Labels: size/L

#422 in case of drawio format, we mush specify an output file
  cmd/analyzer/parse_args.go
Labels: size/XS

#417 408 readme explain
  README.md
Labels: size/S

#418 flag to store resources collected from the cloud provider
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
Labels: size/M

#421 380 abstract vpc and subnet
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L

#426 small fix
  pkg/vpcmodel/nodesExplainability.go
Labels: size/XS

#428 Running golangci-lint action according to docs
  .github/workflows/golangci-lint.yml
Labels: size/XS

#423 340 multiple vpc orig code place
  cmd/analyzer/main.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/unifyGrouping.go
Labels: size/L

#424 340 dont group subnets diff vpc
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff_test.go
Labels: size/L
