Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-07, with the labels that each got.

#656 613 connectivity tgw respond
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_.txt
  pkg/vpcmodel/nodesConnectivity.go
Labels: size/M

#640 support zones in routing tables, wip
  cmd/analyzer/subcmds/analysis.go
  cmd/analyzer/subcmds/explain.go
  cmd/analyzer/subcmds/report.go
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/examples/input/input_hub_n_spoke_multi_region.json
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/routing_tables_test.go
  pkg/ibmvpc/sg_analysis_test.go
  pkg/ibmvpc/vpc.go
Labels: size/XXL

#619 filters split subnets with lb
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_filters_split_lb_subnet.json
  pkg/ibmvpc/examples/out/analysis_out/filters_split_lb_subnet_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/filters_split_lb_subnet_all_vpcs__no_lbAbstract.txt
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/subnetsIPBlocks.go
  pkg/ibmvpc/subnetsIPBlocks_test.go
Labels: size/XXL

#667 Explain report wording improvments
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternalSrcTo4DstInternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPAndRespond_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPRespond_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/TCPRespondPortsQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToVsi_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/M

#631 LB Explainability in HTML
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/multiExplainability.go
  pkg/vpcmodel/nodesConnectivity.go
Labels: size/L

#670 668 detail conn string
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs__debug.txt
  pkg/vpcmodel/detailedConn.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/semanticDiff.go
Labels: size/L

#669 Upgrade to collector v0.12.0
  cmd/analyzer/subcmds/provider.go
  cmd/analyzer/subcmds/root.go
  cmd/analyzer/subcmds/vpcconfigs.go
  go.mod
  go.sum
  release/tag.sh
Labels: size/L

#676 renaming vsi -> endpoint
  pkg/vpcmodel/explainabilityInput.go
Labels: size/M

#678 version v0.5.1
  pkg/version/version.go
Labels: size/XS

#694 update cli flags + readme
  README.md
  cmd/analyzer/main_test.go
  cmd/analyzer/subcmds/diff.go
  cmd/analyzer/subcmds/root.go
  cmd/analyzer/subcmds/vpcconfigs.go
  vpcanalyzer_diff.md
  vpcanalyzer_explain.md
  vpcanalyzer_report.md
Labels: size/L

#691 690 explain path blocked
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/LBToResIPNode_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_debug.txt
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/M

#675 116 lint intrf+first
  cmd/analyzer/subcmds/lint.go
  cmd/analyzer/subcmds/root.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/lint_test.go
  pkg/ibmvpc/vpc.go
  pkg/linter/lintFilterRuleSplitSubnet.go
  pkg/linter/linterExecute.go
  pkg/linter/linterTypes.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L

#703 Issue 702
  pkg/ibmvpc/parser.go
Labels: size/S

#704 Issue 701
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_sg_testing_3_with_empty_remote.json
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_with_empty_remote_all_vpcs_.txt
  pkg/ibmvpc/sg_analysis.go
Labels: size/XXL

#705 version v0.5.2
  pkg/version/version.go
Labels: size/XS

#698 504 explain rule of filter intr
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/rulesDetailsProvider.go
Labels: size/L

#648 aws sg analysis
  cmd/analyzer/main_test.go
  cmd/analyzer/subcmds/vpcconfigs.go
  ola.json
  pkg/awsvpc/analysis_output_test.go
  pkg/awsvpc/examples/.gitignore
  pkg/awsvpc/examples/input/input_aws_sg_1.json
  pkg/awsvpc/examples/input/input_basic_config_with_sg.json
  pkg/awsvpc/examples/out/analysis_out/aws_sg_1_all_vpcs_.txt
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_.txt
  pkg/awsvpc/parser.go
  pkg/awsvpc/sg_analysis.go
  pkg/awsvpc/sg_analysis_test.go
  pkg/commonvpc/connectivity_result.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/sg_analysis.go
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/implicit_routing_test.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/parser_test.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/sg_analysis_test.go
  pkg/ibmvpc/subnetsIPBlocks.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
Labels: size/XXL

#717 Initial html aws
  pkg/awsvpc/analysis_output_test.go
  pkg/commonvpc/parser.go
  pkg/vpcmodel/rulesDetailsProvider.go
Labels: size/S

#719 bug fix - routers are ignored in non-grouping mode
  pkg/vpcmodel/drawioOutput.go
Labels: size/S

#722 540 lint non connected tables new
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/lint_out/PartialTCPRespond_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_partly_overlap_Lint
  pkg/ibmvpc/vpc.go
  pkg/linter/lintBlockedTCPReposnse.go
  pkg/linter/lintFilterRuleSplitSubnet.go
  pkg/linter/lintOverlappingSubnets.go
  pkg/linter/lintRedundantTables.go
  pkg/linter/linterExecute.go
  pkg/linter/linterTypes.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/rulesDetailsProvider.go
Labels: size/L

#725 710 splitted subnet seperate sg nacl
  pkg/ibmvpc/examples/out/lint_out/PartialTCPRespond_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_partly_overlap_Lint
  pkg/linter/lintFilterRuleSplitSubnetCommon.go
  pkg/linter/lintFilterRuleSplitSubnetNACL.go
  pkg/linter/lintFilterRuleSplitSubnetSG.go
  pkg/linter/linterExecute.go
Labels: size/L

#727 fixing resolveGroupedSubnetsOverlap()
  pkg/drawio/layout.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_fabricated.json
Labels: bug, size/XXL

#728 adding SetExternalDestinations() to router interface
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
Labels: size/S

#729 Move code for igw
  pkg/commonvpc/parser.go
  pkg/ibmvpc/parser.go
Labels: size/L

#734 Inital aws drawio
  cmd/analyzer/subcmds/analysis.go
  pkg/awsvpc/analysis_output_test.go
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/drawio/iconTreeNode.go
  pkg/drawio/styles.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/output.go
Labels: size/L, drawio

#739 Set default provider for drawio
  cmd/analyzer/subcmds/analysis.go
  pkg/awsvpc/analysis_output_test.go
  pkg/awsvpc/parser.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/parser_test.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/multi_vpc_config.go
  pkg/vpcmodel/output.go
Labels: size/M
