Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-06, with the labels that each got.

#598 Report lb abstraction
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/.gitignore
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs__with_grouping.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/commonConnectivity.go
  pkg/vpcmodel/connectivityAbstraction.go
  pkg/vpcmodel/debugOutput.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/textOutput.go
Labels: size/L

#610 fix issue with NACL splitting subnet connectivity
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_nacl_split_subnet.json
  pkg/ibmvpc/examples/out/analysis_out/nacl_split_subnet_all_vpcs_.txt
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/XXL

#612 Avoid printing usage message on semantic errors
  cmd/analyzer/main.go
  cmd/analyzer/main_test.go
  cmd/analyzer/subcmds/analysis.go
  cmd/analyzer/subcmds/diff.go
  cmd/analyzer/subcmds/explain.go
  cmd/analyzer/subcmds/report.go
  pkg/ibmvpc/examples/input/input_split_subnet.json
  pkg/logging/logger.go
Labels: size/XXL

#623 do not create html & svg
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/.gitignore
Labels: size/XS

#606 255 stateful connectivity refactor
  cmd/analyzer/expected_out/multi_vpc_configs.txt
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/nacl_split_subnet_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/vpcmodel/commonConnectivity.go
  pkg/vpcmodel/connectivityAbstraction.go
  pkg/vpcmodel/detailedConn.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/multiExplainability.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/XXL

#599 routing tables analysis, phase 3
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/implicit_routing_test.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/routing_tables_test.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/multi_vpc_config.go
  pkg/vpcmodel/routing_paths.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/XXL

#629 Bump github.com/np-guard/cloud-resource-collector from 0.10.2 to 0.11.0
  cmd/analyzer/subcmds/provider.go
  go.mod
  go.sum
Labels: size/L

#622 analyze config files based on provider from config input
  cmd/analyzer/subcmds/provider.go
  cmd/analyzer/subcmds/vpcconfigs.go
  pkg/ibmvpc/examples/input/input_acl_testing3.json
Labels: size/M

#604 Routing analysis wip - support config object input
  cmd/analyzer/main_test.go
  cmd/analyzer/subcmds/analysis.go
  cmd/analyzer/subcmds/report.go
  pkg/common/pair.go
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/examples/input/input_hub_n_spoke_1.json
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/routing_tables_test.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/multi_vpc_config.go
Labels: size/XXL

#634 255 stateful models refactor
  go.mod
  go.sum
  pkg/vpcmodel/commonConnectivity.go
  pkg/vpcmodel/detailedConn.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/responsive_test.go
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/L

#645 Using IPBlock.Overlap()
  go.mod
  go.sum
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/S, Low prio

#636 Lb abstaction bug
  pkg/vpcmodel/connectivityAbstraction.go
  pkg/vpcmodel/connectivityAbstration_test.go
Labels: size/L

#642 614 detail conn
  cmd/analyzer/expected_out/multi_vpc_configs.txt
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/nacl_split_subnet_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs__debug.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_respond_partly_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/vpcmodel/detailedConn.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
Labels: size/L

#649 update parser warnings
  pkg/ibmvpc/parser.go
Labels: size/S

#652 too many bypass points in layout
  pkg/drawio/layoutOverlap.go
  pkg/ibmvpc/analysis_output_test.go
Labels: size/S

#654 Lb not abstracted with tg
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/analysis_out/hub_n_spoke_1_all_vpcs__with_grouping.txt
  pkg/ibmvpc/parser.go
Labels: size/XL

#650 614 conn detail diff single line
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_sg_testing1_copy.json
  pkg/ibmvpc/examples/input/input_sg_testing1_copy_2nd.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new_respond_partly_2nd.json
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing5_all_vpcs_subnetsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_copy_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_respond_partly_all_vpcs_endpointsDiff.txt
  pkg/ibmvpc/examples/out/analysis_out/sg_testing_3_all_vpcs_endpointsDiff.txt
  pkg/vpcmodel/detailedConn.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
Labels: size/XXL
