Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-04, with the labels that each got.

#493 removed unused code
  pkg/ibmvpc/resources.go
Labels: size/XS

#494 update makefile
  Makefile
Labels: size/XS

#497 Parser updates
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
Labels: size/L

#495 412 grouping uid
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_sg_testing1_new_dup_subnets_names.json
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_new_dup_subnets_names_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
Labels: size/XXL

#499 support input from multiple config objects
  README.md
  cmd/analyzer/expected_out/multi_vpc_configs.txt
  cmd/analyzer/main.go
  cmd/analyzer/main_test.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
Labels: size/L

#486 html graph connectivity
  .gitignore
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/drawio/abstractTreeNode.go
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/drawio/iconTreeNode.go
  pkg/drawio/nodesRelations.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
  pkg/drawio/treeNodeInterface.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/output.go
Labels: size/XXL

#507 system implicit routing + routing path type
  go.mod
  go.sum
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/implicit_routing_test.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/routing_paths.go
  pkg/vpcmodel/routing_paths_test.go
Labels: size/L

#510 Add logger for info/warning/error messages handling
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/parser.go
  pkg/logging/logger.go
Labels: size/L

#508 routing tables analysis wip
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/routing_tables_test.go
Labels: size/XL

#517 version v0.4.0-rc.1
  pkg/version/version.go
Labels: size/XS

#509 368 explain iks nodes new
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/L

#512 489 explain no tgw new
  pkg/ibmvpc/examples/out/explain_out/multiVPCNoCrossVPCRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCByAddrNoTgw_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCNoTgw_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/L

#524 Bump github.com/np-guard/cloud-resource-collector from 0.10.0 to 0.10.1
  go.mod
  go.sum
Labels: size/L

#526 update config files to support the new required field in SG rules
  pkg/ibmvpc/examples/input/input_acl_testing3.json
  pkg/ibmvpc/examples/input/input_acl_testing3_2nd.json
  pkg/ibmvpc/examples/input/input_acl_testing3_3rd.json
  pkg/ibmvpc/examples/input/input_acl_testing3_4th.json
  pkg/ibmvpc/examples/input/input_acl_testing3_with_two_vpcs.json
  pkg/ibmvpc/examples/input/input_acl_testing5.json
  pkg/ibmvpc/examples/input/input_acl_testing5_2nd.json
  pkg/ibmvpc/examples/input/input_acl_testing5_old.json
  pkg/ibmvpc/examples/input/input_demo_with_instances.json
  pkg/ibmvpc/examples/input/input_demo_with_instances_vpes.json
  pkg/ibmvpc/examples/input/input_experiments_env.json
  pkg/ibmvpc/examples/input/input_iks_config_object.json
  pkg/ibmvpc/examples/input/input_iks_workers_large.json
  pkg/ibmvpc/examples/input/input_load_balancer.json
  pkg/ibmvpc/examples/input/input_mult_NIs_single_VSI.json
  pkg/ibmvpc/examples/input/input_multiVpc_larger_example_dup_names.json
  pkg/ibmvpc/examples/input/input_multi_regions.json
  pkg/ibmvpc/examples/input/input_multi_resource_groups.json
  pkg/ibmvpc/examples/input/input_multiple_vpcs.json
  pkg/ibmvpc/examples/input/input_obj_from_issue_342.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new_2SGs.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new_2nd.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new_dup_subnets_names.json
  pkg/ibmvpc/examples/input/input_sg_testing1_new_grouping.json
  pkg/ibmvpc/examples/input/input_sg_testing_3.json
  pkg/ibmvpc/examples/input/input_sg_testing_default.json
  pkg/ibmvpc/examples/input/input_tg-prefix-filters.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_multiple_regions.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_with_some_default_deny.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example_dup_names.json
Labels: size/XXL

#528 Explain minor print improve
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_debug.txt
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/M

#532 removed tautological cond (vscode)
  pkg/vpcmodel/explainabilityConnectivity.go
Labels: size/XS

#540 cosmetic error messages improvements
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityInput.go
Labels: size/M

#538 cosmetic outputs improvements
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternalSrcTo4DstInternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryAllowSubset_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCNoCrossVPCRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCByAddrNoTgw_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCNoTgw_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToVsi_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_debug.txt
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/L

#543 Html improvments
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/createMapFile.go
Labels: size/M

#536 471 explain all to all
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/multiExplainability.go
Labels: size/L

#547 534 src dst equal
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityInput.go
Labels: size/M

#546 541 explain cosmetic
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/M

#552 Drawio to stdout
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/vpcmodel/drawioOutput.go
Labels: size/L

#556 Bump github.com/IBM/networking-go-sdk and github.com/IBM/cloud-resource-collector
  go.mod
  go.sum
Labels: size/M

#557 version v0.4.0
  pkg/version/version.go
Labels: size/XS
