Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-09, with the labels that each got.

#804 Add vni example
  go.mod
  go.sum
  pkg/awsvpc/parser.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/vpc.go
  pkg/drawio/drawio_test.go
  pkg/drawio/iconTreeNode.go
  pkg/drawio/styles.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/examples/input/input_vni_basic.json
  pkg/ibmvpc/examples/out/analysis_out/vni_basic_all_vpcs__with_grouping.txt
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/implicit_routing_test.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/vpcmodel/multi_vpc_config.go
Labels: size/XXL

#850 Update for-loop linters for go version 1.22+
  .golangci.yml
  cmd/analyzer/main_test.go
Labels: size/XS

#853 fix nacl name
  pkg/awsvpc/nacl_analysis.go
Labels: size/XS

#843 842 explain private subnet block
  pkg/awsvpc/examples/input/input_aws_sg_1_allow_sg_private.json
  pkg/awsvpc/examples/out/explain_out/from_external_public_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/nacl_blocking_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/same_subnet_no_connection_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/same_subnet_partial_connection_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_blocked_only_private_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_private_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_public_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/explainability_test.go
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsNeitherEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_detail.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/rulesDetailsProvider.go
Labels: size/XXL

#838 support multi-vpc in synthesis output
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing4_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing5_all_vpcs_subnetsBased_withPGW.json
  pkg/ibmvpc/examples/out/synthesis_out/experiments_env_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/multiple_vpcs_all_vpcs_subnetsBased_withPGW.json
  pkg/ibmvpc/synthesis_output_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/synthesisOutput.go
Labels: size/XXL

#848 support bidirectional synthesis
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing4_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing5_all_vpcs_subnetsBased_withPGW.json
  pkg/ibmvpc/examples/out/synthesis_out/experiments_env_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/multiple_vpcs_all_vpcs_subnetsBased_withPGW.json
  pkg/vpcmodel/synthesisOutput.go
Labels: size/XL

#857 support explainability for public node square
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/createMapFile.go
  pkg/drawio/nodesRelations.go
  pkg/drawio/squareTreeNode.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/multiExplainability.go
  pkg/vpcmodel/multi_vpc_config.go
  pkg/vpcmodel/unifyGrouping.go
Labels: size/L

#868 862 table partly allows
  pkg/awsvpc/examples/out/explain_out/from_external_public_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_blocked_only_private_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_private_subnet_all_vpcs_explain_detail.txt
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryAllowSubset_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPAndRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/TCPRespondPortsQuery_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsNeitherEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsOneEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/externalToSubnet_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/subnetToVsiSingleVpc_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_detail.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/rulesDetailsProvider.go
Labels: size/L

#873 Tgw at non multi config
  pkg/awsvpc/vpc.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioOutput.go
Labels: size/S

#874 simplified code and removed redundant code
  pkg/vpcmodel/explainabilityConnectivity.go
Labels: size/M

#872 859 explain empty intersection
  pkg/awsvpc/examples/out/explain_out/nacl_blocking_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/subnet_to_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_blocked_only_private_subnet_all_vpcs_explain_detail.txt
  pkg/awsvpc/examples/out/explain_out/to_external_private_subnet_all_vpcs_explain_detail.txt
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/LBToResIPNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsNeitherEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/externalToSubnet_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCNoCrossVPCRouter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCByAddrNoTgw_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCSameNamesCrossVPCNoTgw_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/subnetToVsiSingleVpc_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwSubnetToSubnet_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_detail.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
Labels: size/L

#879 version v0.6.1
  pkg/version/version.go
Labels: size/XS

#880 added a diff test focused on non-trivial manipulations on the ports
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_sg_testing1_diff_ports.json
  pkg/ibmvpc/examples/input/input_sg_testing1_diff_ports_2nd.json
  pkg/ibmvpc/examples/out/analysis_out/sg_testing1_diff_ports_all_vpcs_endpointsDiff.txt
Labels: size/XXL

#870 support segments synthesis
  go.mod
  go.sum
  pkg/ibmvpc/examples/input/input_subnet_grouping.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing5_all_vpcs_subnetsBased_withPGW_with_grouping.json
  pkg/ibmvpc/examples/out/synthesis_out/subnet_grouping_all_vpcs_subnetsBased_withPGW_with_grouping.json
  pkg/ibmvpc/synthesis_output_test.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/synthesisOutput.go
Labels: size/XXL

#882 remove hard coded tests
  pkg/ibmvpc/explainability_test.go
Labels: size/M

#878 fix current tests with overlapping address prefixes + Remove function
  pkg/ibmvpc/examples/input/input_multi_regions.json
  pkg/ibmvpc/examples/input/input_multi_resource_groups.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_multiple_regions.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_with_some_default_deny.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example_dup_names.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example_partly_overlap.json
  pkg/ibmvpc/tgw_analysis.go
Labels: size/XL

#884 851 lint aws tests
  pkg/awsvpc/examples/out/lint_out/aws_acl1_Lint
  pkg/awsvpc/examples/out/lint_out/aws_mixed_Lint
  pkg/awsvpc/examples/out/lint_out/aws_sg_1_Lint
  pkg/awsvpc/lint_test.go
Labels: size/L

#883 Use the new map/slice features in Go 1.23
  go.mod
  pkg/common/genericSet.go
  pkg/drawio/layout.go
  pkg/linter/linterExecute.go
Labels: size/M

#890 Fix two small things in lint README
  docs/vpcanalyzer_lint.md
Labels: size/XS

#891 887 integrate lint in flow
  cmd/analyzer/subcmds/lint.go
  pkg/commonvpc/testfunc/lint_test_functionality.go
  pkg/linter/linterExecute.go
  pkg/linter/linterTypes.go
Labels: size/M

#865 refactor Name() and ExtendedName(c) methods
  pkg/awsvpc/parser.go
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/experiments_env_all_vpcs_.json
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/routing_tables_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/linter/lintTCPReposnseBlocked.go
  pkg/linter/lintUnattached.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/mdOutput.go
  pkg/vpcmodel/multiExplainability.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/routing_paths.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/synthesisOutput.go
  pkg/vpcmodel/textOutput.go
  pkg/vpcmodel/unifyGrouping.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L
