Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-03, with the labels that each got.

#431 391 explainability filter internal
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping_test.go
Labels: size/L

#419 creating svg file
  .gitignore
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/createMapFile.go
  pkg/drawio/iconTreeNode.go
  pkg/drawio/layoutOverlap.go
  pkg/drawio/styles.go
Labels: size/XL

#436 Remove `--new` flag from golangci-lint
  Makefile
Labels: size/XS

#438 if the input is not a legal cidr/IP address then the error message sh…
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityInput.go
Labels: size/M

#425 Allow using -resource-group and -region flags to filter resources from -vpc-config
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_multi_regions.json
  pkg/ibmvpc/examples/input/input_multi_resource_groups.json
  pkg/ibmvpc/examples/out/analysis_out/multi_regions_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/multi_resource_groups_all_vpcs_.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/parser.go
Labels: size/XXL

#444 store the information about filtered nodes (uids) while parsing
  pkg/ibmvpc/parser.go
Labels: size/S

#459 Line formating
  pkg/drawio/styles.go
Labels: size/S

#462 sort before printing to avoid inconsistency in tests
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/sg_analysis.go
Labels: size/S

#451 add region field to the resources model
  pkg/ibmvpc/examples/input/input_acl_testing3.json
  pkg/ibmvpc/examples/input/input_demo_with_instances.json
  pkg/ibmvpc/examples/input/input_experiments_env.json
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/demo_with_instances_all_vpcs_subnetsBased_withPGW.json
  pkg/ibmvpc/examples/out/analysis_out/experiments_env_all_vpcs_.json
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/parser_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping_test.go
Labels: size/XXL

#465 Region in drawio
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
  pkg/ibmvpc/ibmDrawioGenerator.go
Labels: size/L

#463 Bump models to v0.2.1
  .cspell/custom-dictionary-workspace.txt
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  go.mod
  go.sum
  pkg/common/connectionset.go
  pkg/common/statefulness.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/connectivity_result.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/parser_test.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/XL

#472 387 add external ip to fip
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_debug.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/S

#464 454 explain multivpc input with vpc
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityInput.go
Labels: size/M

#458 454 explainability multivpc
  cmd/analyzer/main.go
  cmd/analyzer/parse_args.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_tgw_larger_example_dup_names.json
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal3_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternalSrcTo4DstInternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryAllowSubset_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG2_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToVsi_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/parser.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/unifyGrouping.go
Labels: size/XXL

#468 write tests for main()
  cmd/analyzer/main_test.go
Labels: size/L

#475 sort before printing tables
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_debug.txt
  pkg/ibmvpc/vpc.go
Labels: size/S

#474 Bump models to v0.3.0
  .cspell/custom-dictionary-workspace.txt
  cmd/analyzer/parse_args.go
  go.mod
  go.sum
  pkg/common/connectionset.go
  pkg/common/connectionset_test.go
  pkg/common/statefulness.go
  pkg/common/statefulness_test.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/connectivity_result.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/commonConnectivity.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/jsonOutput.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/semanticDiff.go
  pkg/vpcmodel/semanticDiff_test.go
  pkg/vpcmodel/subnetsConnectivity.go
  pkg/vpcmodel/utils.go
  pkg/vpcmodel/vpcConfig.go
  pkg/vpcmodel/vpcConnectivity.go
Labels: size/XXL

#461 452 grouping selfloop bug
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_iks_workers_large_shorter_names.json
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_shorter_names_all_vpcs__with_grouping.txt
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/groupingSelfLoop.go
Labels: size/XXL

#473 450 grouping pointers bug
  pkg/common/genericSet.go
  pkg/ibmvpc/groupingUnification_test.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/unifyGrouping.go
Labels: size/L

#460 Load balancer
  pkg/drawio/abstractTreeNode.go
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/iconTreeNode.go
  pkg/drawio/layout.go
  pkg/drawio/styles.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L

#476 Bump github.com/np-guard/cloud-resource-collector from 0.5.2 to 0.10.0
  go.mod
  go.sum
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/input/input_acl_testing5.json
  pkg/ibmvpc/examples/input/input_acl_testing5_2nd.json
  pkg/ibmvpc/examples/input/input_acl_testing5_old.json
  pkg/ibmvpc/examples/input/input_demo_with_instances.json
  pkg/ibmvpc/examples/input/input_demo_with_instances_vpes.json
  pkg/ibmvpc/examples/input/input_experiments_env.json
  pkg/ibmvpc/examples/input/input_iks_config_object.json
  pkg/ibmvpc/examples/input/input_iks_workers_large.json
  pkg/ibmvpc/examples/input/input_iks_workers_large_shorter_names.json
  pkg/ibmvpc/examples/input/input_load_balancer.json
  pkg/ibmvpc/examples/input/input_multi_regions.json
  pkg/ibmvpc/examples/input/input_multi_resource_groups.json
  pkg/ibmvpc/examples/input/input_multiple_vpcs.json
  pkg/ibmvpc/examples/input/input_obj_from_issue_342.json
  pkg/ibmvpc/examples/input/input_sg_testing_3.json
  pkg/ibmvpc/examples/input/input_tg-prefix-filters.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_multiple_regions.json
  pkg/ibmvpc/examples/input/input_tgw_basic_example_with_some_default_deny.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example.json
  pkg/ibmvpc/examples/input/input_tgw_larger_example_dup_names.json
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_shorter_names_all_vpcs__with_grouping.txt
  pkg/ibmvpc/parser.go
Labels: size/XXL
