Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-05, with the labels that each got.

#567 moving gomnd to mnd
  .golangci.yml
  pkg/drawio/layoutOverlap.go
  pkg/drawio/styles.go
  pkg/drawio/subnetLayoutOverlap.go
Labels: size/S

#564 521 rule with sg
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi4_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_debug.txt
  pkg/ibmvpc/sg_analysis.go
  pkg/ibmvpc/sg_analysis_test.go
Labels: size/L

#559 521 vpc name
  pkg/ibmvpc/examples/out/analysis_out/multi_regions_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tg-prefix-filters_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_multiple_regions_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_multiple_regions_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_basic_example_with_some_default_deny_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW.txt
  pkg/ibmvpc/examples/out/analysis_out/tgw_larger_example_all_vpcs_subnetsBased_withPGW_with_grouping.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/textOutput.go
Labels: size/XL

#570 Grouping unification tets
  pkg/ibmvpc/groupingUnification_test.go
Labels: size/XS

#550 rewriting getAll*
  pkg/drawio/createMapFile.go
  pkg/drawio/layout.go
  pkg/drawio/layoutOverlap.go
  pkg/drawio/nodesRelations.go
  pkg/drawio/subnetsLayout.go
  pkg/drawio/treeNodeInterface.go
Labels: size/L

#571 consistency in the return values of VPC.AddressRange() and VPC.AddressPrefixes()
  pkg/ibmvpc/implicit_routing.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
Labels: size/XS

#533 Load balancer abstraction
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/examples/input/input_iks_w_lb.json
  pkg/ibmvpc/examples/input/input_lb_bad_practice.json
  pkg/ibmvpc/examples/input/input_lb_policies.json
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/connectivityAbstraction.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/semanticDiff.go
Labels: size/XXL

#575 Multi sg in drawio
  pkg/common/genericSet.go
  pkg/drawio/createMapFile.go
  pkg/drawio/drawio_test.go
  pkg/drawio/iconTreeNode.go
  pkg/drawio/layout.go
  pkg/drawio/squareTreeNode.go
Labels: size/L

#578 Optimize subnet grouping
  pkg/drawio/drawio_test.go
  pkg/drawio/subnetsLayout.go
Labels: size/M

#572 multipleVPCConfigs as a struct
  cmd/analyzer/main.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/groupingUnification_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/parser_test.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/multiExplainability.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/unifyGrouping.go
  pkg/vpcmodel/vpcConfig.go
Labels: size/L

#573 Use cobra to parse cmdline args - phase 1
  README.md
  cmd/analyzer/main.go
  cmd/analyzer/main_test.go
  cmd/analyzer/parse_args.go
  cmd/analyzer/subcmds/diff.go
  cmd/analyzer/subcmds/explain.go
  cmd/analyzer/subcmds/format.go
  cmd/analyzer/subcmds/protocol.go
  cmd/analyzer/subcmds/provider.go
  cmd/analyzer/subcmds/report.go
  cmd/analyzer/subcmds/root.go
  cmd/gendocs/main.go
  go.mod
  go.sum
  pkg/vpcmodel/output.go
  vpcanalyzer_diff.md
  vpcanalyzer_explain.md
  vpcanalyzer_report.md
Labels: size/XXL

#586 enable filters and LB on subnet mode
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
Labels: size/S

#574 504 unify tgw explain structs + multiple prefixes single connection
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_debug.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_debug.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/tgw_analysis.go
  pkg/ibmvpc/tgw_analysis_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityInput.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
Labels: size/XL

#588 add "load blalncer" prefix to reports
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/vpc.go
Labels: size/L

#585 handle empty squares on subnet mode
  pkg/drawio/drawio_test.go
  pkg/drawio/layout.go
  pkg/drawio/subnetsLayout.go
Labels: size/L

#587 Using cobra to parse command-line args - phase 2
  cmd/analyzer/main.go
  cmd/analyzer/subcmds/analysis.go
  cmd/analyzer/subcmds/diff.go
  cmd/analyzer/subcmds/explain.go
  cmd/analyzer/subcmds/format.go
  cmd/analyzer/subcmds/report.go
  cmd/analyzer/subcmds/root.go
  cmd/analyzer/subcmds/vpcconfigs.go
  cmd/gendocs/main.go
Labels: size/XL

#591 Non lb abstraction mode
  cmd/analyzer/subcmds/analysis.go
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/iconTreeNode.go
  pkg/drawio/styles.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/groupingUnification_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/output.go
Labels: size/XL
