Repository np-guard/vpc-network-config-analyzer, pull requests merged in 2024-08, with the labels that each got.

#741 Drawio gpw on subnet mode
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioOutput.go
Labels: size/M

#744 743 fix PartialTCPRespond lint bug
  pkg/ibmvpc/examples/out/lint_out/acl3_3rd_Lint
  pkg/ibmvpc/lint_test.go
  pkg/linter/lintBlockedTCPReposnse.go
Labels: size/M

#749 Drawio for aws
  pkg/drawio/connectivityMap.drawio.tmpl
  pkg/drawio/connectivityMap.svg.tmpl
  pkg/drawio/drawio_test.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
Labels: size/L, drawio, aws

#733 create internet gateway resource
  pkg/awsvpc/awsDrawioGenerator.go
  pkg/awsvpc/examples/out/analysis_out/aws_sg_1_all_vpcs_.txt
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_.txt
  pkg/awsvpc/parser.go
  pkg/awsvpc/vpc.go
  pkg/commonvpc/parser.go
  pkg/ibmvpc/parser.go
Labels: size/L

#755 Public subnets for igw
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_.txt
  pkg/awsvpc/parser.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/vpc.go
Labels: size/M

#753 711 enable disable mechanism
  cmd/analyzer/subcmds/lint.go
  cmd/analyzer/subcmds/root.go
  pkg/ibmvpc/lint_test.go
  pkg/linter/lintFilterRuleSplitSubnetSG.go
  pkg/linter/lintRedundantTables.go
  pkg/linter/linterExecute.go
Labels: size/L

#754 Lint inheritence
  cmd/analyzer/subcmds/lint.go
  pkg/common/genericSet.go
  pkg/ibmvpc/lint_test.go
  pkg/linter/lintBlockedTCPReposnse.go
  pkg/linter/lintFilterRuleSplitSubnetCommon.go
  pkg/linter/lintFilterRuleSplitSubnetNACL.go
  pkg/linter/lintFilterRuleSplitSubnetSG.go
  pkg/linter/lintOverlappingSubnets.go
  pkg/linter/lintRedundantTables.go
  pkg/linter/lintRuleNonRelevantCIDRCommon.go
  pkg/linter/lintRuleNonRelevantCIDRNACL.go
  pkg/linter/lintRuleNonRelevantCIDRSG.go
  pkg/linter/linterExecute.go
  pkg/linter/linterTypes.go
Labels: size/L

#732 AWS nacl analysis
  cmd/analyzer/main_test.go
  go.mod
  pkg/awsvpc/analysis_output_test.go
  pkg/awsvpc/examples/input/input_aws_acl_1.json
  pkg/awsvpc/examples/out/analysis_out/aws_acl_1_all_vpcs_.txt
  pkg/awsvpc/examples/out/analysis_out/aws_acl_1_all_vpcs_subnetsBased_withPGW.txt
  pkg/awsvpc/examples/out/analysis_out/aws_sg_1_all_vpcs_subnetsBased_withPGW.txt
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_subnetsBased_withPGW.txt
  pkg/awsvpc/nacl_analysis.go
  pkg/awsvpc/parser.go
  pkg/awsvpc/sg_analysis.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/nacl_analysis.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/connectivityAnalysis_test.go
  pkg/ibmvpc/ibmDrawioGenerator.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/vpc.go
Labels: size/XXL

#760 Union drawio conn
  pkg/vpcmodel/drawioOutput.go
Labels: size/M

#764 Lint testing enable disable
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_other_lints_disabled_Lint
  pkg/ibmvpc/lint_test.go
Labels: size/S

#766 Grouping points on space
  pkg/drawio/layout.go
Labels: size/M

#770 762 subnet location in path
  .gitignore
  cmd/analyzer/expected_out/acl_testing3_detailed_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/LBToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLOnlyDenyNoConnQuery_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryAllowSubset_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPAndRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/TCPRespondPortsQuery_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsNeitherEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsOneEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToVsi_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisablesTCPRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_detail.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/L

#773 List supported VPC resources
  README.md
  docs/supported_resources.md
  docs/vpcanalyzer_diff.md
  docs/vpcanalyzer_explain.md
  docs/vpcanalyzer_report.md
Labels: size/M

#778 remove not needed file
  ola.json
Labels: size/XXL

#777 761 nacl fip
  cmd/analyzer/expected_out/multi_vpc_configs.txt
  cmd/analyzer/expected_out/non_abstracted_load_balancer.txt
  pkg/awsvpc/vpc.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.md
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/hub_n_spoke_1_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGSubsetPorts_all_vpcs_explain_detail.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/nodesConnectivity.go
Labels: size/XXL

#789 757 unattached seperate nacl sg
  pkg/awsvpc/parser.go
  pkg/commonvpc/parser.go
  pkg/ibmvpc/examples/out/lint_out/PartialTCPRespond_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_3rd_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_partly_overlap_Lint
  pkg/ibmvpc/lint_test.go
  pkg/ibmvpc/parser.go
  pkg/linter/lintUnattached.go
  pkg/linter/linterExecute.go
  pkg/logging/logger.go
Labels: size/L

#791 Specifying an output file in the CLI suppresses output to stdout
  cmd/analyzer/subcmds/analysis.go
Labels: size/XS

#792 757 lint names
  pkg/ibmvpc/lint_test.go
  pkg/linter/lintRuleCIDROutOfRange.go
  pkg/linter/lintRuleShadowedOrImplied.go
  pkg/linter/lintRuleSplitSubnet.go
  pkg/linter/lintSubnetCIDROverlap.go
  pkg/linter/lintTCPReposnseBlocked.go
  pkg/linter/linterExecute.go
Labels: size/M

#775 aws public subnet explainability
  pkg/awsvpc/parser.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/vpc.go
  pkg/drawio/drawio_test.go
  pkg/drawio/squareTreeNode.go
  pkg/drawio/styles.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/semanticDiff_test.go
Labels: size/M

#786 fix sg name
  pkg/awsvpc/examples/input/input_aws_acl_1.json
  pkg/awsvpc/examples/input/input_aws_sg_1.json
  pkg/awsvpc/examples/input/input_basic_config_with_sg.json
  pkg/awsvpc/examples/out/analysis_out/aws_sg_1_all_vpcs_.txt
  pkg/awsvpc/examples/out/analysis_out/aws_sg_1_all_vpcs_subnetsBased_withPGW.txt
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_.txt
  pkg/awsvpc/examples/out/analysis_out/basic_config_with_sg_all_vpcs_subnetsBased_withPGW.txt
  pkg/awsvpc/parser.go
  pkg/awsvpc/sg_analysis.go
  pkg/commonvpc/parser.go
  pkg/ibmvpc/parser.go
Labels: size/XL

#788 Pip tcp response
  cmd/analyzer/expected_out/non_abstracted_load_balancer.txt
  pkg/ibmvpc/examples/out/analysis_out/filters_split_lb_subnet_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/filters_split_lb_subnet_all_vpcs__no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/hub_n_spoke_1_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_config_object_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/iks_workers_large_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs_.txt
  pkg/ibmvpc/examples/out/analysis_out/lb_bad_practice_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping.txt
  pkg/ibmvpc/examples/out/analysis_out/load_balancer_all_vpcs__with_grouping_no_lbAbstract.txt
  pkg/ibmvpc/examples/out/analysis_out/nacl_split_subnet_all_vpcs_.txt
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/nodesConnectivity.go
Labels: size/XL

#802 771 icmp rulestr
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/LBToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeNoProtocolConn_all_vpcs_explain_detail.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/sg_analysis.go
Labels: size/M

#795 757 lint format text
  pkg/ibmvpc/examples/out/lint_out/PartialTCPRespond_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_3rd_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_other_lints_disabled_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_partly_overlap_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_print_all_Lint
  pkg/linter/lintRuleCIDROutOfRange.go
  pkg/linter/lintRuleShadowedOrImplied.go
  pkg/linter/lintRuleSplitSubnet.go
  pkg/linter/lintSubnetCIDROverlap.go
  pkg/linter/lintTCPReposnseBlocked.go
  pkg/linter/lintUnattached.go
Labels: size/L

#799 757 readme
  README.md
  docs/vpcanalyzer_lint.md
  pkg/ibmvpc/examples/out/lint_out/PartialTCPRespond_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_3rd_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_Lint
  pkg/ibmvpc/examples/out/lint_out/acl3_shadowed_rules_other_lints_disabled_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_acl3_Lint
  pkg/ibmvpc/examples/out/lint_out/basic_sg1_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_partly_overlap_Lint
  pkg/ibmvpc/examples/out/lint_out/multivpc_print_all_Lint
  pkg/linter/lintRuleCIDROutOfRange.go
  pkg/linter/lintRuleShadowedOrImplied.go
Labels: size/L

#806 Exp aws example platform
  pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt
  pkg/awsvpc/explainability_test.go
  pkg/commonvpc/analysis_output_test_functionality.go
  pkg/ibmvpc/explainability_test.go
Labels: size/L

#810 809 explain subnet path
  cmd/analyzer/expected_out/acl_testing3_detailed_explain.txt
  pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/GroupingExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/IksNodeToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/LBToIksNode_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLExternal1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLGrouping_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLInternal2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryAllowSubset_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnection1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/NACLQueryConnectionRules4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPAndRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/PartialTCPRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGBasic4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/QueryConnectionSGRules4_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/TCPRespondPortsQuery_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi1_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi2_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi3_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiToVsi5_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsNeitherEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgsOneEnabling_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/VsiWithTwoSgs_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiNIsToSingleNI_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternal_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToVsi_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherEnableDefaultDifFile_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwAnotherExampleEnabledConn_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisabledDenyPrefix_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwDisablesTCPRespond_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnableDefaultFilter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwEnabledSpecificFilter_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/tgwExampleCidr_all_vpcs_explain_detail.txt
  pkg/ibmvpc/examples/out/explain_out/vpeToIksNodeSubsetRules_all_vpcs_explain_detail.txt
  pkg/ibmvpc/explainability_test.go
  pkg/vpcmodel/explainabilityPrint.go
Labels: size/L

#688 basic support for synthesis output format
  cmd/analyzer/subcmds/format.go
  pkg/awsvpc/parser.go
  pkg/commonvpc/analysis_output_test_functionality.go
  pkg/commonvpc/drawioGenerator.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/vpc.go
  pkg/ibmvpc/egress_routing_test.go
  pkg/ibmvpc/examples/input/input_acl_testing4.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing3_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing4_all_vpcs_.json
  pkg/ibmvpc/examples/out/synthesis_out/acl_testing5_all_vpcs_subnetsBased_withPGW.json
  pkg/ibmvpc/implicit_routing_test.go
  pkg/ibmvpc/ingress_routing_test.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/synthesis_output_test.go
  pkg/ibmvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/drawioGenerator.go
  pkg/vpcmodel/drawioOutput.go
  pkg/vpcmodel/externalNetwork.go
  pkg/vpcmodel/formattableResource.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/output.go
  pkg/vpcmodel/synthesisOutput.go
Labels: size/XXL

#821 Allow setting the --provider flag to aws
  cmd/analyzer/subcmds/vpcconfigs.go
  pkg/awsvpc/parser.go
  pkg/ibmvpc/parser.go
Labels: size/M

#817 fix sg rule description
  pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt
  pkg/awsvpc/sg_analysis.go
  pkg/awsvpc/sg_analysis_test.go
Labels: size/S

#797 add documentation and capture more common code
  pkg/awsvpc/nacl_analysis.go
  pkg/awsvpc/parser.go
  pkg/awsvpc/sg_analysis.go
  pkg/commonvpc/nacl_analysis.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/sg_analysis.go
  pkg/ibmvpc/nacl_analysis.go
  pkg/ibmvpc/parser.go
  pkg/ibmvpc/sg_analysis.go
Labels: size/L

#819 Support rule number
  pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt
  pkg/awsvpc/nacl_analysis.go
Labels: size/S

#827 Extend --vpc cli arg to support multiple values
  cmd/analyzer/subcmds/root.go
  cmd/analyzer/subcmds/vpcconfigs.go
  pkg/awsvpc/parser.go
  pkg/commonvpc/analysis_output_test_functionality.go
  pkg/commonvpc/parser.go
  pkg/ibmvpc/analysis_output_test.go
  pkg/ibmvpc/examples/out/analysis_out/acl_testing3_with_two_vpcs_crn12.txt
  pkg/ibmvpc/examples/out/analysis_out/experiments_env_crn1crn17.txt
  pkg/ibmvpc/explainability_test.go
  pkg/ibmvpc/naclAnalysis_test.go
  pkg/ibmvpc/parser.go
Labels: size/M

#828 Private subnet connectivity and explainability
  pkg/awsvpc/parser.go
  pkg/commonvpc/parser.go
  pkg/commonvpc/vpc.go
  pkg/vpcmodel/abstractVPC.go
  pkg/vpcmodel/explainabilityConnectivity.go
  pkg/vpcmodel/explainabilityPrint.go
  pkg/vpcmodel/grouping.go
  pkg/vpcmodel/grouping_test.go
  pkg/vpcmodel/nodesConnectivity.go
  pkg/vpcmodel/subnetsConnectivity.go
Labels: size/L

#830 move lint test functionality to commonvpc
  pkg/commonvpc/analysis_output_test_functionality.go
  pkg/ibmvpc/lint_test.go
Labels: size/L

#837 Get sg name
  pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt
  pkg/awsvpc/parser.go
  pkg/awsvpc/sg_analysis.go
Labels: size/S
